# Generated by Django 5.0.6 on 2026-04-05 01:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=20, verbose_name='peran')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama kategori')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.category', verbose_name='kategori induk')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama matkul')),
                ('description', models.TextField(default='-', verbose_name='deskripsi')),
                ('price', models.IntegerField(default=10000, verbose_name='harga')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='kategori')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='pengajar')),
            ],
            options={
                'verbose_name': 'Mata Kuliah',
                'verbose_name_plural': 'Mata Kuliah',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='judul konten')),
                ('description', models.TextField(default='-', verbose_name='deskripsi')),
                ('video_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL Video')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='urutan')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course', verbose_name='matkul')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='courses.coursecontent', verbose_name='induk')),
            ],
            options={
                'verbose_name': 'Konten Kelas',
                'verbose_name_plural': 'Konten Kelas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('std', 'Siswa'), ('ast', 'Asisten')], default='std', max_length=3, verbose_name='peran')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course', verbose_name='matkul')),
                ('user_id', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='siswa')),
            ],
            options={
                'verbose_name': 'Anggota Kelas',
                'verbose_name_plural': 'Anggota Kelas',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='komentar')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent', verbose_name='konten')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemember', verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='selesai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu selesai')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.coursecontent', verbose_name='konten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.coursemember', verbose_name='anggota')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='idx_course_name'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='idx_course_price'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('member', 'content')},
        ),
    ]
